title: "React 19の新機能まるわかり"
summary: "2024年4月にリリースされたReact 19 Betaの新機能について、細かい点やポイントを解説します。"
topics: ["react"]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - actions
  - useactionstate
  - form-action
  - use-optimistic
  - use
  - resources
  - context
  - ref-cleanup
  - ref-prop
  - use-deferred-value
  - error-handling
  - upgrade
